language: php
php:
  - '8.2'
sudo: false
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
script:
  - php vendor/bin/codecept run unit
branches:
  only:
    - 2.0
dist: focal
addons:
  apt:
    packages:
      - libonig5